name: release

on:
  push:
    tags:
      - '202?.?.*'


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node-
      - run: make dep
      - run: make test

#  # broken at the moment;
#  release-any:
#    runs-on: ubuntu-latest
#    needs:
#      - test
#    env:
#      RELEASE_SFTP_KEY: ${{ secrets.RELEASE_SFTP_KEY }}
#      RELEASE_SFTP_URI: ${{ secrets.RELEASE_SFTP_URI }}
#    steps:
#      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '12'
#      - uses: actions/cache@v2
#        if: ${{ !env.ACT }}
#        with:
#          path: ~/.npm
#          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: ${{ runner.OS }}-node-
#      - run: yarn global add modclean
#      - run: make dep release
#      - run: make upload
#        if: ${{ !env.ACT }}

  release-docker:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t cortezaproject/corteza-server-corredor:${{ env.BUILD_VERSION }} .
        if: ${{ !env.ACT }}
      - run: docker push cortezaproject/corteza-server-corredor:${{ env.BUILD_VERSION }}
        if: ${{ !env.ACT }}
